### ISSUE TITLE
MoViNet-A0 block 2 should have 40 out channels

### ISSUE THREAD

**Issue by SMHendryx** [Atze00/MoViNet-pytorch#14]
Nit: per the paper, there should be 40 output channels in block 2 for MoViNet-A0, while this implementation currently has 24.
https://github.com/Atze00/MoViNet-pytorch/blob/2ad697facd370d01b0f3a6093d38211166e594de/movinets/config.py#L62

https://arxiv.org/pdf/2103.11511.pdf

**Comment by Atze00** [comment]
There are some modification with respect to the original paper. These modifications are made by the authors in their own official implementation, probably the paper is not updated to the latest results.
Have a look here: 
https://github.com/tensorflow/models/blob/master/official/vision/beta/projects/movinet/modeling/movinet.py

**Comment by SMHendryx** [comment]
Thanks @Atze00 for the info. Closing this issue.
