### ISSUE TITLE
Error in  running movinet-pytorch to onnx converted model

### ISSUE THREAD

**Issue by papasanimohansrinivas** [Atze00/MoViNet-pytorch#18]
Hi @Atze00 

![error_important](https://user-images.githubusercontent.com/13809378/136567761-d32559f3-9854-4e80-8e0c-0268531404b4.PNG)

**I succesfully transfer trained this repos movinets**

**But i want to deploy it else where into tensorrt format**

**So i first converted pytorch model to onnx using torch.onnx.export**

**I wanted to verify whether model is correctly ported . So I ran it in onnxruntime**

**It is throwing error like in the screenshot**

**Suggest any solutions**

**kindly help me here**

**let me know if any more screenshots or anything else**

**Comment by Atze00** [comment]
I would suggest you avoid screenshots, the code should be reported in text. The same is true also for the errors, in fact the error messages are also incomplete.
This may help [https://github.com/onnx/onnx/issues/3192](https://github.com/onnx/onnx/issues/3192).
You could try to convert the model with pretrained = False and  tf_like = False. If it works there could be problems related to the fact that this architecture emulates tensorflow models.

**Comment by papasanimohansrinivas** [comment]
hi @Atze00  I did a mistake of saving model as it is in` torch.save` meaning `torch.save(model)` instead of recommended way of `torch.save(model.state_dict(),PATH)` which led to this all nonsense 

1. onnx converted and excuted with out error 

2. I have yet to run sanity tests like onnx output and this repo output is matching on some videos 

3. Now i am proceeding to export this pytorch model to tensorrt , there are some hiccups like oom 

Thanks @Atze00  your repo model implementation is giving satisfactory results on our use case

**Comment by Atze00** [comment]
Glad to hear that!

**Comment by papasanimohansrinivas** [comment]
@Atze00  i am closing this ticket as its purpose is served , just one request is there any fundamental way to speed up bare pytorch on jetson for movinets , i tried other options but they are giving same speed as bare pytorch.

Anything from your experience would be a lot helpful than u know
