### ISSUE TITLE
MoViNets are now open source

### ISSUE THREAD

**Issue by Hyperparticle** [Atze00/MoViNet-pytorch#2]
Just FYI, the official implementation has been released at https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet

**Comment by Atze00** [comment]
Thank you, I'll look into it!

**Comment by Atze00** [comment]
All the pre-trained models are available also in PyTorch. 
Looking forward to the stream version

**Comment by zhangyuan1994511** [comment]
Thank you for your good implementation! Could you provide more detail training code or example?

**Comment by zhangyuan1994511** [comment]
@Atze00

**Comment by Hyperparticle** [comment]
Streaming models are now available here https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet#streaming-models. There should be a code sample on how to use it.

**Comment by Atze00** [comment]
Nice work and thank you for the update.

**Comment by YongdongTan** [comment]
> All the pre-trained models are available also in PyTorch.
> Looking forward to the stream version

How tensorflow weights are used in pytorch
