### ISSUE TITLE
Using MoViNet in a dataset with variable-length videos

### ISSUE THREAD

**Issue by alexlopezcifuentes** [Atze00/MoViNet-pytorch#20]
Hi!

Thanks for the work to bring this paper to PyTorch.

I was wondering how can we use MoViNet training with the stream buffer when we don't have videos with the same number of frames.

Authors of the paper claimed, in Section 4, that they used the method in Charades Dataset: _"[...] Charades [53], which has variable-length videos with 157 action classes where a video can contain multiple class annotations."_ However, they don't specify which policy they used when training with variable-length videos. They also report results on the EPIC Kitchens Dataset which is also variable-length.

Do you have any insights into how they may have trained these models? The main issue here is how to build a batch when temporal dimensions are not the same...

Thank you!

**Comment by Atze00** [comment]
Hi! If I remember well the paper explains that they repeat the clips that are shorter than the input length.
