### ISSUE TITLE
Test model based on 'evaluate_stream' is ok, but do inference frame by frame is very different?

### ISSUE THREAD

**Issue by erwangccc** [Atze00/MoViNet-pytorch#24]
Train 'a0' model by clip=1, Tclip=8, and the acc on my custom test dataset is good, but when the model do inference for online video stream, recognition is not good as test dataset. In fact, test dataset if's from the video stream i use, so i believe their domain is same.

Online demo read one frame from video stream and concatente with previous 7 frames, then input to model, so the model do inference with 8 frames too.

code for online video stream is as follows:

```
if isinstance(new_frame, torch.Tensor):
      torch_inputs = torch.cat((tensor_fifo[:, :, 1:, :, :], new_frame), 2)
else:
      cvt_img = cv2.cvtColor(new_frame, cv2.COLOR_BGR2RGB)
      cvt_img = np.transpose(cvt_img, (2, 0, 1))
      cvt_img = cvt_img[:, np.newaxis, :, :][np.newaxis, :, :, :, :]
      torch_inputs = np.concatenate((tensor_fifo[:, :, 1:, :, :],
                                     cvt_img), 2)
```

**Comment by Atze00** [comment]
You don't need to concatenate if you use the stream version. You should read more carefully how the stream buffer works before asking me here. I'm just a guy who decided to open source some code he developed, I'm not here to explain how the features introduced in the paper work. 
Any question that is not related to my code, for example questions about how the features introduced in the paper work, are not to be asked here.

**Comment by erwangccc** [comment]
> You don't need to concatenate if you use the stream version. You should read more carefully how the stream buffer works before asking me here. I'm just a guy who decided to open source some code he developed, I'm not here to explain how the features introduced in the paper work. Any question that is not related to my code, for example questions about how the features introduced in the paper work, are not to be asked here.

Alright. u can delete this issue
