### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Atze00** [Atze00/MoViNet-pytorch#3]
Thank you for your good implementation! Could you provide more detail training code or example?

_Originally posted by @zhangyuan1994511 in https://github.com/Atze00/MoViNet-pytorch/issues/2#issuecomment-842952447_

**Comment by Atze00** [comment]
Can you elaborate? 
There is a training loop example in the readme

**Comment by zhangyuan1994511** [comment]
@Atze00
Thank you for your replay. What I mean is the complete training code, including dataloader、model etc.

**Comment by Atze00** [comment]
You can use any PyTorch training code. There is nothing particular to this architecture except for the training loop of which there is already an example. 
I will upload anyway an example of fine-tuning on HMDB51 once I've cleaned up the code a little bit.

**Comment by zhangyuan1994511** [comment]
@Atze00
OK, Looking forward your complete training code, it's will help me a lot! Thank you very much!

**Comment by Atze00** [comment]
It is available a simple training code for the dataset HMDB-51
