### ISSUE TITLE
F.ToFloatTensorInZeroOne not exist

### ISSUE THREAD

**Issue by haowei2020** [Atze00/MoViNet-pytorch#30]
Did you define you own transforms? I can't import ToFloatTensorInZeroOne() from torchvision.transforms. And I find that type of video returned from torchvision.datasets.HMDB51() is tensor, dtype=torch.uint8, so just divide 255.0 ? 
![Snipaste_2022-04-01_16-09-01](https://user-images.githubusercontent.com/82873816/161222638-991c7437-4caa-498a-a038-f53550585549.jpg)

**Comment by haowei2020** [comment]
[](url
[transforms.zip](https://github.com/Atze00/MoViNet-pytorch/files/8477250/transforms.zip)
)

**Comment by ZipHouse0383** [comment]
Is that the same with transforms.ToTensor()? This transforms will divide 255.0  additionally.
