### ISSUE TITLE
pretrain dataset?

### ISSUE THREAD

**Issue by pacifinapacific** [Atze00/MoViNet-pytorch#4]
Thanks for the great work, what dataset did you use for the pretrain weights?
Is it possible to provide the weights for the kinetics dataset?

**Comment by Atze00** [comment]
The weights are the same as the pre-trained models on Tensorflow (on kinetics), released by the authors. 
I will update the readme to make it more clear and provide some tests that verify that the two networks are equivalent.

**Comment by pacifinapacific** [comment]
Thank you very much for your time.
