### ISSUE TITLE
Does this implementation supports Streaming Buffer and Causal Conv?

### ISSUE THREAD

**Issue by IgorSondors** [Atze00/MoViNet-pytorch#5]

**Comment by Atze00** [comment]
Currently you only have the only the option for the causal behavior, It will automatically use the stream buffer. Take a look at the examples in the readme and let me know if they are not clear. 
You can choose to not use the stream buffer by providing the full clip as input to the model and deleting the cached activation right after. 
I may consider to separate the two options in the future, but as for today I don't see a reason to do so.
