### ISSUE TITLE
transform for test video in movinet_tutorial.ipynb

### ISSUE THREAD

**Issue by Billchen1993** [Atze00/MoViNet-pytorch#7]
In movinet_tutorial.ipynb, video transform for test dataset should be transform_test rather than transform I guess. Namely, hmdb51_test = torchvision.datasets.HMDB51('video_data/', 'test_train_splits/', num_frames,frame_rate=5,
                                                step_between_clips = clip_steps, fold=1, train=False,
                                                transform=transform_test, num_workers=2)

**Comment by Atze00** [comment]
thank you for the issue
